### ISSUE TITLE
Doesn't compile with Facebook SDK

### ISSUE THREAD

**Issue by Vandallord** [uerceg/play-install-referrer-unity#1]
**Describe the bug**
If you insert the plugin into the project and facebook SDK, then the project will stop compiling

**To Reproduce**
Create a project in Unity 2019.4.19 (I think it will be with all versions). Paste the latest facebook SDK (all versions I tried didn't work) and try to compile the project

**Expected behaviour**
I need so that I can compile a project that has this plugin and facebook SDK

**Environment**
Please describe your working environment:
- **play-install-referrer-unity** plugin version v3.0.0
- Unity IDE version 2019.4.19
- Android API 30

**Additional context**
Hi I found the plugin doesn't work with facebook sdk. What could be the reason?
I think it has to do with some kind of dependency conflict. tried to change the version of the plugin, facebook does not help. How to fix it?

**Comment by Vandallord** [comment]
Solved a problem. The problem was that the facebook sdk library version is 1.0. You have version 2.1 in the plugin. And in the third SDK, which version 1.2 conflicts with.

**Comment by uerceg** [comment]
Hi @Vandallord 

And oh my, sorry for being late in replying to this ticket. Glad to see it being solved. I'm gonna close the ticket, but just to ask - does it compile nicely now in your app with all those native libraries being part of your app's project?
